apiVersion: apps/v1
kind: Deployment
metadata:
  name: dronesim-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dronesim-app
  template:
    metadata:
      labels:
        app: dronesim-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "dronesim-app-id"
        dapr.io/app-port: "8282"
        dapr.io/config: "dapr-cp-config"
    spec:
      containers:
        - name: dronesim-app
          image: com.hha/dronesim:latest
          ports:
            - containerPort: 8282
          env:
            - name: SPRING_KAFKA_BOOTSTRAP-SERVERS
              value: host.minikube.internal:9093
            - name: TZ
              value: Europe/Berlin
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: dronesim-app
spec:
  selector:
    app: dronesim-app
  ports:
    - port: 80
      targetPort: 8282
  type: LoadBalancer
