apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: dapr-sidecar-config
  namespace: default
spec:
  tracing:
    samplingRate: "1"
    zipkin:
      endpointAddress: http://host.minikube.internal:9411/api/v2/spans
