apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
  namespace: default
spec:
  type: pubsub.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: pubsub.urlBrokerHostMachine
      key: pubsub.urlBrokerHostMachine
  - name: redisPassword
    secretKeyRef:
      name: pubsub.redisPassword
      key: pubsub.redisPassword
auth:
  secretStore: secret-store-local-file
scopes:
  - rentadrone-app-id
  - smarttracker-app-id
