apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store-azurekeyvault-rentadrone
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    secretKeyRef:
      name: secret-store-azurekeyvault-rentadrone.vaultName
      key: secret-store-azurekeyvault-rentadrone.vaultName
  - name: azureTenantId
    secretKeyRef:
      name: secret-store-azurekeyvault-rentadrone.azureTenantId
      key: secret-store-azurekeyvault-rentadrone.azureTenantId
  - name: azureClientId
    secretKeyRef:
      name: secret-store-azurekeyvault-rentadrone.azureClientId
      key: secret-store-azurekeyvault-rentadrone.azureClientId
  - name: azureClientSecret
    secretKeyRef:
      name: secret-store-azurekeyvault-rentadrone.azureClientSecret
      key: secret-store-azurekeyvault-rentadrone.azureClientSecret
auth:
  secretStore: secret-store-local-file
scopes:
  - rentadrone-app-id
  - smarttracker-app-id
