apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store-local-file
  namespace: default
spec:
  type: secretstores.local.file
  version: v1  
  metadata:
  - name: secretsFile
    value: ../dapr/secrets.json
  - name: nestedSeparator
    value: "."
scopes:
  - rentadrone-app-id
  - smarttracker-app-id
