apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secret-store-azurekeyvault-rentadrone
  namespace: default
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    secretKeyRef:
      name: secret-store-azurekeyvault-secret
      key: vaultName
  - name: azureTenantId
    secretKeyRef:
      name: secret-store-azurekeyvault-secret
      key: azureTenantId
  - name: azureClientId
    secretKeyRef:
      name: secret-store-azurekeyvault-secret
      key: azureClientId
  - name: azureClientSecret
    secretKeyRef:
      name: secret-store-azurekeyvault-secret
      key: azureClientSecret
scopes:
  - rentadrone-app-id
  - smarttracker-app-id
