apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: default
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    secretKeyRef:
      name: statestore-secret
      key: urlBrokerHostMachine
  - name: redisPassword
    secretKeyRef:
      name: statestore-secret
      key: redisPassword
  - name: actorStateStore
    value: "true"
  - name: keyPrefix
    value: none
scopes:
  - rentadrone-app-id
  - smarttracker-app-id
